# AntiFarm plugin configuration file.

# General settings.
settings:
   # Prefix to be used in messages to players.
   prefix: "&a[AntiFarm]&r "
   # Send plugin stats to bstats.
   bstats: true
   # Check for plugin updates.
   update-check: true
   # Break detected pistons for auto farm. ('true' option is recommended for performance.)
   break-pistons: true
   # Break detected blocks for auto farm. ('true' option is recommended for performance.)
   break-blocks: true
   # List of worlds you want to disable anti farm. (Case sensitive list.)
   disabled-worlds:
   - "TheNameOfWorldYouWantToDisable"
   - "AnotherWorld"

# Anti afk fish farm settings.
anti-fishing:
   # Enable/Disable option.
   enable: true
   # Send warning message when player is blocked.
   warn: true
   # Warning message.
   warn-msg: "&cYou have reached the fishing limit in the same area, go to different areas to continue fishing!"
   # Get kicked off the server if the player keeps fishing.
   kick: false
   # Kicking message.
   kick-msg: "&cYou were kicked from the server due to afk fish farm!"
   # How many times can the player fish per chunk? (Fails do not count.)
   caught-fish-per-chunk: 10
   # Time to wait to fish again in the same chunk. (Default: 10 min = 600 seconds.)
   chunk-cooldown: 600

# Mob spawner settings.
mob-spawner-settings:
   # Prevent mob spawner from spawning creatures.
   prevent-spawn: true
   # Prevent players from breaking mob spawner. (Admins can still break it by sneak and hitting.)
   prevent-break: true
   # Preventing mob spawners from being converted by clicking with mob eggs.
   prevent-transformation: true
   # Warning message to player.
   player-warn-message: "&cYou can't break mob spawner, this action blocked on server!"
   # Warning message to admin.
   admin-warn-message: "&cMob spawner break is disabled on server. But you are an admin and if you want to break, you can. (Sneak + Attack)"
   # Transformation blocking message to admin.
   transformation-warn-message: "&cYou can't convert mob spawner, this action is blocked on server!"
   # Spawner data customization.
   spawner-data:
      # Enable/Disable option.
      enable: false
      # Spawners.
      spawners:
         # Spawner's type (zombie, skeleton, etc).
         exampleSpawner:
            # Set the maximum number of similar entities that are allowed to be within spawning range of this spawner.
            maxNearbyEntities: 6
            # Set the maximum spawn delay amount (in ticks) (20 ticks = 1 second).
            maxSpawnDelay: 800
            # Set the minimum spawn delay amount (in ticks) (20 ticks = 1 second).
            minSpawnDelay: 200
            # Set the maximum distance (squared) a player can be in order for this spawner to be active.
            requiredPlayerRange: 16
            # Set how many mobs attempt to spawn.
            spawnCount: 4
            # Set the new spawn range.
            spawnRange: 4
         zombie:
            maxNearbyEntities: 6
            maxSpawnDelay: 800
            minSpawnDelay: 200
            requiredPlayerRange: 16
            spawnCount: 4
            spawnRange: 4

# Villager settings.
villager-settings:
   # Once the villager gets a profession it prevents it from being changed.
   prevent-villagers-profession-change: true
   # Prevents villagers from harvesting and planting fields.
   prevent-villagers-harvesting-farms: true
   # Prevent villagers from breeding.
   prevent-villagers-breed: true
   # Prevents villagers from getting infected. (This blocks the way to get discounts from villagers on your server.)
   prevent-villagers-infection: true
   # Prevent zombie villagers from being cured. (This makes it difficult to reach villagers on your server, making them valuable.)
   prevent-zombie-villagers-cure: true
   # Prevents villagers from being targeted by creatures. (Helps protect the villager population.)
   prevent-targeting-villager: true
   # Prevents trade with villagers.
   prevent-villager-trade: false
   # Prevents trade with wandering traders.
   prevent-wandering-trader-trade: false
   # Disables iron golem spawning with villager interaction.
   prevent-golem-spawning:
      # Prevents iron golem spawning when villager is scared or attacked.
      village-defense: true
      # Prevents iron golem spawning when the village is raiding.
      village-raids: true

# Automatic farms settings.
farms-settings:
   # Prevents farming by placing a block next to the cactus.
   prevent-cactus-farms: true
   # Prevents 'farm-blocks' from breaking and moving with piston.
   prevent-piston-farms: true
   # Prevents harvesting farm blocks using water.
   prevent-water-harvesting-farms: true
   # Prevents farm blocks from being taken by endermans.
   prevent-enderman-harvesting-farms: true
   # Prevents planting on a block of land that has not reached the full water level.
   prevent-waterless-farms: true
   # Prevents planting on farmland with light level below 8.
   prevent-lightless-farms: true
   # Prevents the snowman from leaving snow trail on the ground.
   prevent-snowball-farms: true
   # Prevents foxes from dropping sweet berries to the ground.
   prevent-berry-farms: true
   # Prevents 'farmland-blocks' with 'farm-blocks' from being moved by pistons.
   prevent-zerotick-farms: true

# Dispenser settings.
dispenser-settings:
   # Prevent bone meal throwing with dispenser.
   prevent-bonemeal: true
   # Prevent shearing sheep with dispenser.
   prevent-shearing: true

# Automatic mob farms settings.
prevent-mob-farms:
   # Enable/Disable option.
   enable: true
   # Percentage of damage the player must inflict for the mob to loot.
   required-damage-percent-for-loot: 80
   # All afk mob farms are blocked by default.
   # If you only want to block only one creature's farm. Set 'blacklist' to 'true' and add the name of the creature you want to block to the 'moblist'.
   # If you only want to allow only one creature's farm. Set 'blacklist' to 'false' and add the name of the creature you want to block to the 'moblist'.
   # If you want all afk creature farms to be blocked don't touch the default settings.
   blacklist: false
   # blacklist: true -> 'moblist' is blacklist.
   # blacklist: false -> 'moblist' is whitelist.
   # When adding mobs to the list, all letters should be capitalized. (Case sensitive list.)
   moblist:
   - BAT

# Raid farms settings.
prevent-raid-farms:
   # Enable/Disable option.
   enable: true
   # Cooldown between raids. (Seconds.)
   cooldown: 600

# Froglight farms settings.
prevent-froglight-farms:
   # Enable/Disable option.
   enable: true
   # Limit of froglight that a frog can produce in its lifetime.
   count: 5

# List of blocks on which any farm block can be grown.
farmland-blocks:
- GRASS_BLOCK
- DIRT
- COARSE_DIRT
- ROOTED_DIRT
- SAND
- RED_SAND
- FARMLAND
- SOUL_SAND
- END_STONE

# List of all things that can be farmed.
farm-blocks:
- CACTUS
- SUGAR_CANE
- SUGAR_CANE_BLOCK
- REEDS
- BAMBOO
- MELON
- MELON_STEM
- MELON_BLOCK
- ATTACHED_MELON_STEM
- PUMPKIN
- PUMPKIN_STEM
- ATTACHED_PUMKIN_STEM
- WHEAT
- CROPS
- CARROT
- CARROTS
- POTATO
- POTATOES
- BEETROOT
- BEETROOTS
- BEETROOT_BLOCK
- SWEET_BERRY_BUSH
- COCOA
- CAVE_VINES
- CAVE_VINES_PLANT
- NETHER_WART
- CHORUS_PLANT
- CHORUS_FLOWER
- RED_MUSHROOM
- BROWN_MUSHROOM
- CRIMSON_FUNGUS
- WARPED_FUNGUS
- MOSS_BLOCK
- KELP