disable-farms:
   water-farm: true
   piston-farm: true
   cactus-farm: true
   enderman-farm: true
   villager-farm: true
   light-level-farm: true
   waterless-farm: true
disable-mob-farms:
   all-mob-farms: true
   iron-farm: true
   gold-farm: true
   villager-breed: true
disable-mob-spawner:
   spawn-prevent: true
   break-prevent: true
   player-warn-message: "&cYou can't break mob spawner, this action blocked on server."
   admin-warn-message: "&cMob spawner break is disabled on server. But you are an admin and if you want to break, you can. (Sneak + Attack)"
disable-fish-farms:
   enable: true
   warn: true
   warn-msg: "&cYou have reached the fishing limit in the same area, go to different areas to continue fishing!"
   kick: false
   kick-msg: "&cYou were kicked from the server due to afk fish farm!"
   caught-fish-per-chunk: 10
   chunk-cooldown: 600
settings:
   prefix: "&a[antiFarm]&r "
   break-pistons: true
   break-farm-blocks: true
   block-dispense-bonemeal: true
   block-villager-damage: true
   block-villager-infection: true
   block-zombie-villager-cure: false
farm-blocks:
- CACTUS
- SUGAR_CANE
- BAMBOO
- MELON
- MELON_STEM
- ATTACHED_MELON_STEM
- PUMPKIN
- PUMPKIN_STEM
- ATTACHED_PUMKIN_STEM
- WHEAT
- CARROTS
- POTATOES
- BEETROOTS
- SWEET_BERRY_BUSH
- COCOA
- CAVE_VINES
- CAVE_VINES_PLANT
- NETHER_WART
- CHORUS_PLANT
- CHORUS_FLOWER
- RED_MUSHROOM
- BROWN_MUSHROOM
- CRIMSON_FUNGUS
- WARPED_FUNGUS
- MOSS_BLOCK
- KELP